version: '3'

services:
  mssql:
    container_name: 'mssql_server'
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - ${MSSQL_PORT}:1433
    env_file:
      - .env
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
